# Generated by Django 5.1.1 on 2024-12-11 02:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dealer_app', '0006_alter_cnote_freight_alter_cnote_grand_total'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartyMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_code', models.CharField(max_length=50, unique=True)),
                ('party_name', models.CharField(max_length=100)),
                ('display_name', models.CharField(max_length=100)),
                ('mobile_number_1', models.CharField(max_length=15)),
                ('mobile_number_2', models.CharField(blank=True, max_length=15)),
                ('phone_number_1', models.CharField(blank=True, max_length=15)),
                ('phone_number_2', models.CharField(blank=True, max_length=15)),
                ('gst_no', models.CharField(blank=True, max_length=15)),
                ('pan_no', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('marketing_person', models.CharField(blank=True, max_length=100)),
                ('party_type', models.CharField(max_length=50)),
                ('country', models.CharField(default='INDIA', max_length=50)),
                ('state', models.CharField(blank=True, max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=6)),
                ('address', models.TextField()),
                ('is_tbb', models.BooleanField(default=False)),
                ('remark', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('capital', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transporter_app.state')),
            ],
        ),
        migrations.CreateModel(
            name='Transporter',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('transporter_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('company_name', models.CharField(default='Unknown Company', max_length=100)),
                ('contact_person', models.CharField(default='Unknown Contact Person', max_length=100)),
                ('phone_number_1', models.CharField(max_length=15)),
                ('phone_number_2', models.CharField(blank=True, max_length=15, null=True)),
                ('mobile_number_1', models.CharField(max_length=15)),
                ('mobile_number_2', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('gstn', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.TextField(default='Address not provided')),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle_number', models.CharField(default='UNKNOWN', max_length=20)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transporter_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transporter',
                'verbose_name_plural': 'Transporters',
                'db_table': 'transporter',
            },
        ),
        migrations.CreateModel(
            name='Pickup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('picked_up', 'Picked Up'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('pickup_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cnote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dealer_app.cnote')),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dealer_app.dealer')),
                ('transporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transporter_app.transporter')),
            ],
        ),
        migrations.CreateModel(
            name='TransporterProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transporter_profile_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
