# Generated by Django 5.1.1 on 2024-12-19 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer_app', '0010_alter_loadingsheetdetail_cnote'),
        ('transporter_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransporterAppReceive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ls_number', models.CharField(max_length=50, unique=True)),
                ('received_date', models.DateTimeField(auto_now_add=True)),
                ('total_lrs', models.IntegerField()),
                ('total_art', models.IntegerField()),
                ('total_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('from_branch', models.CharField(max_length=100)),
                ('to_branch', models.CharField(max_length=100)),
                ('truck_no', models.CharField(max_length=20)),
                ('ls_date_time', models.DateTimeField()),
                ('dealer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dealer_app.dealer')),
                ('transporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transporter_app.transporter')),
            ],
        ),
    ]
