# Generated by Django 5.1.1 on 2024-12-21 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporter_app', '0002_transporterappreceive'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceivedStatesCnotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnote_number', models.CharField(max_length=255)),
                ('consignor_name', models.CharField(max_length=255)),
                ('consignee_name', models.CharField(max_length=255)),
                ('consignor_contact', models.CharField(max_length=255)),
                ('consignee_contact', models.CharField(max_length=255)),
                ('articles', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ls_number', models.CharField(max_length=255)),
                ('dealer_name', models.CharField(max_length=255)),
                ('transporter_name', models.CharField(max_length=255)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Received', max_length=255)),
            ],
        ),
    ]
