# Generated by Django 5.1.1 on 2024-12-22 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporter_app', '0003_receivedstatescnotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='receivedstatescnotes',
            name='godown',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='receivedstatescnotes',
            name='received_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='receivedstatescnotes',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
