# Generated by Django 5.1.1 on 2024-12-26 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporter_app', '0004_receivedstatescnotes_godown_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryCNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lr_number', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=50)),
                ('payment_type', models.CharField(max_length=50)),
                ('consignor_name', models.CharField(max_length=100)),
                ('consignor_address', models.TextField()),
                ('consignor_contact', models.CharField(max_length=15)),
                ('consignor_gst', models.CharField(max_length=15)),
                ('consignee_name', models.CharField(max_length=100)),
                ('consignee_address', models.TextField()),
                ('consignee_contact', models.CharField(max_length=15)),
                ('consignee_gst', models.CharField(max_length=15)),
                ('freight_charges', models.DecimalField(decimal_places=2, max_digits=10)),
                ('other_charges', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delivered_to_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('id_proof_type', models.CharField(max_length=50)),
                ('id_proof_number', models.CharField(max_length=50)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('delivered_status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
