# Generated by Django 5.1.1 on 2024-11-07 16:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dealer_app', '0001_initial'),
        
    ]

    operations = [
        migrations.AddField(
            model_name='dealer',
            name='transporter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dealers', to='transporter_app.transporter'),
        ),
        migrations.AddField(
            model_name='dealer',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cnote',
            name='dealer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dealer_app.dealer'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='cnote',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dealer_app.cnote'),
        ),
        migrations.AddField(
            model_name='cnote',
            name='delivery_destination',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dealer_app.deliverydestination'),
        ),
        migrations.AddField(
            model_name='branch',
            name='delivery_destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dealer_app.deliverydestination'),
        ),
        migrations.AddField(
            model_name='loadingsheet',
            name='cnotes',
            field=models.ManyToManyField(related_name='loading_sheets', to='dealer_app.cnote'),
        ),
        migrations.AddField(
            model_name='loadingsheet',
            name='transporter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='transporter_app.transporter'),
        ),
        migrations.AddField(
            model_name='transporter',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dealer_transporter', to=settings.AUTH_USER_MODEL),
        ),
    ]
