# Generated by Django 5.1.1 on 2024-11-18 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer_app', '0002_initial'),
        ('transporter_app', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoadingSheetSummary',
            fields=[
                ('ls_number', models.AutoField(primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=100)),
                ('total_cnote_number', models.IntegerField(default=0)),
                ('total_paid_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_to_pay_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_tbb', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_foc', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_package', models.IntegerField(default=0)),
                ('state', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dealer_app.dealer')),
                ('transporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transporter_app.transporter')),
            ],
        ),
        migrations.CreateModel(
            name='LoadingSheetDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=100)),
                ('cnote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dealer_app.cnote')),
                ('loading_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='dealer_app.loadingsheetsummary')),
            ],
        ),
    ]
