# Generated by Django 5.1.1 on 2024-11-20 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer_app', '0003_loadingsheetsummary_loadingsheetdetail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loadingsheetdetail',
            old_name='state',
            new_name='consignee_name',
        ),
        migrations.RenameField(
            model_name='loadingsheetsummary',
            old_name='total_cnote_number',
            new_name='total_art',
        ),
        migrations.RenameField(
            model_name='loadingsheetsummary',
            old_name='total_package',
            new_name='total_cnote',
        ),
        migrations.RenameField(
            model_name='loadingsheetsummary',
            old_name='total_foc',
            new_name='total_foc_amount',
        ),
        migrations.RenameField(
            model_name='loadingsheetsummary',
            old_name='total_tbb',
            new_name='total_manual_foc_amount',
        ),
        migrations.RenameField(
            model_name='loadingsheetsummary',
            old_name='total_to_pay_amount',
            new_name='total_manual_paid_amount',
        ),
        migrations.RemoveField(
            model_name='loadingsheetsummary',
            name='city',
        ),
        migrations.RemoveField(
            model_name='loadingsheetsummary',
            name='state',
        ),
        migrations.AddField(
            model_name='cnote',
            name='total_art',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='loadingsheetdetail',
            name='amount',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loadingsheetdetail',
            name='art',
            field=models.IntegerField(default='0'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loadingsheetdetail',
            name='consignee_contact',
            field=models.CharField(default='0000000000', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loadingsheetdetail',
            name='consignor_contact',
            field=models.CharField(default='0000000000', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loadingsheetdetail',
            name='consignor_name',
            field=models.CharField(default='Enter Name', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loadingsheetdetail',
            name='destination',
            field=models.CharField(default='Destination', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loadingsheetdetail',
            name='payment_type',
            field=models.CharField(default='Payment Type', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loadingsheetdetail',
            name='remark',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='loadingsheetdetail',
            name='status',
            field=models.CharField(default='dispatched', max_length=20),
        ),
        migrations.AddField(
            model_name='loadingsheetsummary',
            name='status',
            field=models.CharField(default='dispatched', max_length=20),
        ),
        migrations.AddField(
            model_name='loadingsheetsummary',
            name='total_manual_tbb_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='loadingsheetsummary',
            name='total_manual_topay_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='loadingsheetsummary',
            name='total_tbb_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='loadingsheetsummary',
            name='total_topay_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='loadingsheetdetail',
            name='loading_sheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dealer_app.loadingsheetsummary'),
        ),
    ]
