# Generated by Django 5.1.1 on 2024-11-27 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer_app', '0004_rename_state_loadingsheetdetail_consignee_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transporter',
            name='user',
        ),
        migrations.AlterField(
            model_name='loadingsheetdetail',
            name='cnote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loading_sheet_details', to='dealer_app.cnote'),
        ),
        migrations.AlterField(
            model_name='loadingsheetdetail',
            name='loading_sheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='dealer_app.loadingsheetsummary'),
        ),
        migrations.AlterField(
            model_name='loadingsheetdetail',
            name='status',
            field=models.CharField(choices=[('dispatched', 'Dispatched'), ('received', 'Received'), ('cancelled', 'Cancelled')], default='dispatched', max_length=20),
        ),
        migrations.AlterField(
            model_name='loadingsheetsummary',
            name='status',
            field=models.CharField(choices=[('dispatched', 'Dispatched'), ('received', 'Received'), ('cancelled', 'Cancelled')], default='dispatched', max_length=20),
        ),
        migrations.DeleteModel(
            name='LoadingSheet',
        ),
        migrations.DeleteModel(
            name='Transporter',
        ),
    ]
