# Generated by Django 5.1.1 on 2024-12-09 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
       # ('dealer_app', '0005_remove_transporter_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cnote',
            name='freight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cnote',
            name='grand_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
