# Generated by Django 5.1.1 on 2024-12-11 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dealer_app', '0005_remove_transporter_user_and_more'),
        ('dealer_app', '0006_alter_cnote_freight_alter_cnote_grand_total'),
    ]

    operations = [
    ]
