# Generated by Django 5.1.1 on 2024-12-15 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer_app', '0007_merge_20241211_0824'),
    ]

    operations = [
        migrations.CreateModel(
            name='CNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnote_number', models.CharField(db_index=True, editable=False, max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking_type', models.CharField(choices=[('sundry', 'Sundry'), ('other', 'Other')], default='sundry', max_length=50)),
                ('delivery_type', models.CharField(choices=[('economy', 'Economy'), ('express', 'Express')], default='economy', max_length=50)),
                ('delivery_method', models.CharField(max_length=50)),
                ('eway_bill_number', models.CharField(blank=True, max_length=50, null=True)),
                ('manual_date', models.DateField(blank=True, null=True)),
                ('manual_cnote_number', models.CharField(blank=True, max_length=50, null=True)),
                ('manual_cnote_type', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_type', models.CharField(blank=True, max_length=50, null=True)),
                ('consignor_name', models.CharField(max_length=100)),
                ('consignor_mobile', models.CharField(max_length=15)),
                ('consignor_gst', models.CharField(blank=True, max_length=15, null=True)),
                ('consignor_address', models.TextField(blank=True, null=True)),
                ('consignee_name', models.CharField(max_length=100)),
                ('consignee_mobile', models.CharField(max_length=15)),
                ('consignee_gst', models.CharField(blank=True, max_length=15, null=True)),
                ('consignee_address', models.TextField(blank=True, null=True)),
                ('actual_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('charged_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('weight_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('weight_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fix_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('invoice_number', models.CharField(blank=True, max_length=255, null=True)),
                ('declared_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('risk_type', models.CharField(choices=[('owner', 'Owner'), ('carrier', 'Carrier')], max_length=50)),
                ('pod_required', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('freight', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('docket_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('door_delivery_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('handling_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pickup_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('transhipment_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('insurance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fuel_surcharge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('commission', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('other_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('carrier_risk', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('booked', 'Booked'), ('dispatched', 'Dispatched'), ('received', 'Received'), ('due_for_delivery', 'Due for Delivery'), ('delivered', 'Delivered'), ('received_at_godown', 'Received at Godown'), ('cancelled', 'Cancelled')], default='booked', max_length=20)),
                ('status_updated_at', models.DateTimeField(auto_now=True)),
                ('total_art', models.IntegerField(default=0)),
                ('dealer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dealer_app.dealer')),
                ('delivery_destination', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dealer_app.deliverydestination')),
            ],
        ),
    ]
