# Generated by Django 5.1.1 on 2024-12-18 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer_app', '0009_alter_article_cnote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loadingsheetdetail',
            name='cnote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loading_sheet_details', to='dealer_app.cnotes'),
        ),
    ]
